language: ruby

rvm:
  - "2.1.2"
  - "2.0.0"
  - "1.9.3"
  - jruby-19mode

gemfile:
  - ".gemfiles/Gemfile.rails-3.2.x"
  - ".gemfiles/Gemfile.rails-4.1.x"

before_install:
  - gem install bundler --no-doc
